# Generated by Django 3.2.6 on 2023-09-08 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_digitalservice_marketingservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
