# Generated by Django 3.2.6 on 2023-09-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='other_activity',
            field=models.CharField(max_length=100),
        ),
    ]
