# Generated by Django 3.2.6 on 2023-09-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_solution_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='link',
            field=models.URLField(default='http://127.0.0.1:8000/services'),
        ),
    ]
