# Generated by Django 3.2.6 on 2023-09-08 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_solution_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solution',
            new_name='Service',
        ),
    ]
